name: "CI - Python Tests"

on:
  workflow_call:
    inputs:
      #----Configuracion General----
      python-version:
        description: "Version de Python"
        required: false
        type: string
        default: "3.12"
      
      #----Control de Ejecucion----
      stop-on-fail:
        description: "Si es true, el pipeline se detendra si algo falla"
        required: false
        type: boolean
        default: true

      #----Linter----
      run-lint:
        description: "Ejecutar analisis de codigo (flake8)"
        required: false
        type: boolean
        default: true
      lint-command:
        description: "Comando de linter (opcional)"
        required: false
        type: string
        default: ""

      #----Tests----
      run-tests:
        description: "Ejecutar pruebas unitarias"
        required: false
        type: boolean
        default: true
      test-command:
        description: "Comando para ejecutar pruebas(opcional)"
        required: false
        type: string
        default: ""
    secrets:
      JWT_SECRET_KEY:
        required: false

jobs:
  check-and-test:
    runs-on: ubuntu-latest

    env:
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

    steps: 
      #----Clonar repo----
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      #----Configuraciones de python----
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Instalar dependencias
        run: |
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      #----Linter----
      - name: Ejecutar Linter
        if: ${{ inputs.run-lint }}
        continue-on-error: true
        run: |
          echo "Ejecutando analisis de codigo..."
          mkdir -p reports/lint
          if [ -n "${{ inputs.lint-command }}" ]; then
            echo "Usando comando personalizado de lint..."
            ${{ inputs.lint-command }}
          else
            echo "Usando flake8 por defecto..."
            pip install flake8

            #----Se ejecuta flake8 y se guarda el resultado----
            flake8 . --output-file reports/lint/flake8-report.txt || true
            echo "Reporte generado"
          fi

      #----Tests----
      - name: Ejecutar pruebas
        if: ${{ inputs.run-tests }}
        continue-on-error: ${{ !inputs.stop-on-fail }}
        run: |
          echo "Ejecutando pruebas..."
          mkdir -p reports/tests
          if [ -n "${{ inputs.test-command }}" ]; then
            echo "Ejecutando comando de prueba personalizado"
            ${{ inputs.test-command }}
          else
            echo "Corriendo comando pytest por defecto"
            pip install pytest pytest-cov

            #----Se ejecuta pytest y se guarda el resultado----
            pytest --cov=. \
                   --cov-report=xml:reports/tests/coverage.xml \
                   --cov-report=html:reports/tests/htmlcov \
                   --cov-report=term-missing  -v
            echo "Reporte generado"
          fi

      #----Reporte de Pruebas----
      - name: Generar Reporte de pruebas
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports/
          if-no-files-found: ignore

